site:
  site_name: Global City
  phone: "0903596692"
  zalo_link: https://zalo.me/0903596692
  facebook_link: https://www.facebook.com/batdongsansinhloi68/
  youtube_link: https://www.youtube.com/@phammythanhbds
  website_link: https://batdongsansinhloi.com
  default_seo_description: Global City - thông tin dự án, vị trí, sản phẩm thấp
    tầng và cao tầng. Liên hệ 0903 596 692 để được tư vấn chi tiết.
  email: thanh@batdongsansinhloi.com
